--- #YAML:1.0
name:               Dpchrist-Cvs-NerfTags
version:            1.013
abstract:           disable RCS/CVS tags in working files
author:
    - David Paul Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:        0
    Carp:                 0
    Config:               0
    Cwd:                  0
    Data::Dumper:         0
    Dpchrist::Debug:      1.047
    Dpchrist::ExtUtils::MakeMaker:  1.015
    Dpchrist::LangUtil:   1.015
    Exporter:             0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    File::Find:           0
    File::Path:           0
    File::Spec::Functions:  0
    File::Temp:           0
    FindBin:              0
    Getopt::Long:         0
    Pod::Usage:           0
    Test::Compile:        0
    Test::Manifest:       0
    Test::More:           0
    Test::Pod:            0
    Test::Prereq:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
